
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author zainu
 */
public class barang extends javax.swing.JPanel {

    /**
     * Creates new form barang
     */
    public barang() {
        initComponents();
    reset();
        tampil_tabel_barang();
    }
    
    void tampil_tabel_barang (){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("kode barang");
        model.addColumn("nama barang");
        model.addColumn("stok");
        model.addColumn("harga jual");
        model.addColumn("nama beli");
        try{
            String sql="SELECT * FROM barang";
            java.sql.Connection conn=koneksi.ConfigDB();
            java.sql.Statement statement=conn.createStatement();
            java.sql.ResultSet resultSet=statement.executeQuery(sql);
            while(resultSet.next()){
                model.addRow(new Object[]{resultSet.getString("kode_barang"),resultSet.getString("nama_barang"),resultSet.getString("stok"),resultSet.getString("harga_jual"),resultSet.getString("harga_beli")});
            }
           ttabelbarang.setModel(model);
        }catch (Exception e){
            e.printStackTrace();
            }
        }
    
void reset(){
    idbarang.setText("");
    tnamab.setText("");
    ts.setText("");
    thb.setText("");
    thj.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idbarang = new javax.swing.JTextField();
        tnamab = new javax.swing.JTextField();
        ts = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        thb = new javax.swing.JTextField();
        thj = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttabelbarang = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 250, 255));

        jLabel1.setText("id barang");

        jLabel2.setText("Nama barang");

        jLabel3.setText("Stock");

        idbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarangActionPerformed(evt);
            }
        });

        tnamab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamabActionPerformed(evt);
            }
        });

        ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga beli");

        jLabel5.setText("Harga jual");

        thb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thbActionPerformed(evt);
            }
        });

        thj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thjActionPerformed(evt);
            }
        });

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        ttabelbarang.setBackground(new java.awt.Color(250, 250, 250));
        ttabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttabelbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttabelbarang);

        panel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("barang > Dashboard");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addContainerGap(775, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(17, 51, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Barang");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ts, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tnamab, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idbarang, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(thb)
                                    .addComponent(thj)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(breset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bsimpan))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bubah)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnamab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(thb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(thj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bhapus)
                    .addComponent(breset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bubah)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String kode_barang=idbarang.getText();
        String nama_barang=tnamab.getText();
        String stok=ts.getText();
        String harga_jual=thj.getText();
        String harga_beli=thb.getText();
        try{
            String sql="INSERT INTO barang(id_barang,nama_barang,stok,harga_beli,harga_jual)values('"+kode_barang+"','"+nama_barang+"','"+ stok +"','"+harga_beli+"','"+harga_jual+"')";
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di simpan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_barang();
        reset();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetActionPerformed

    private void ttabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttabelbarangMouseClicked
        // TODO add your handling code here:
        int baris= ttabelbarang.rowAtPoint(evt.getPoint());
        String kode_barang= ttabelbarang.getValueAt(baris, 0).toString();
        String nama_barang= ttabelbarang.getValueAt(baris, 1).toString();
        String stock = ttabelbarang.getValueAt(baris, 2).toString();
        String harga_beli= ttabelbarang.getValueAt(baris, 3).toString();
        String harga_jual= ttabelbarang.getValueAt(baris, 4).toString();
         idbarang.setText(kode_barang);
         tnamab.setText(nama_barang);
         ts.setText(stock);
         thb.setText(harga_beli);
         thj.setText(harga_jual);
         idbarang.setEditable(false);
         
         
       
    }//GEN-LAST:event_ttabelbarangMouseClicked

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        String kode_barang=idbarang.getText();
        
        try{
            String sql="DELETE FROM barang WHERE kode_barang='"+kode_barang+"'";
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_barang();
        reset();
    }//GEN-LAST:event_bhapusActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
         String kode_barang=idbarang.getText();
        String nama_barang=tnamab.getText();
        String stock=ts.getText();
        String harga_jual=thj.getText();
        String harga_beli=thb.getText();
        try{
          String sql = "UPDATE barang SET nama_barang='" + nama_barang + "', stock='" + stock + "', harga_jual='" + harga_jual + "', harga_beli='" + harga_beli + "' WHERE kode_barang='" + kode_barang + "'";
           
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di ubah");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_barang();
        reset();
    }//GEN-LAST:event_bubahActionPerformed

    private void idbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarangActionPerformed

    private void tnamabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamabActionPerformed

    private void thbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thbActionPerformed

    private void thjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thjActionPerformed

    private void tsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JTextField idbarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JTextField thb;
    private javax.swing.JTextField thj;
    private javax.swing.JTextField tnamab;
    private javax.swing.JTextField ts;
    private javax.swing.JTable ttabelbarang;
    // End of variables declaration//GEN-END:variables
}
