
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author zainu
 */
public class listbarang extends javax.swing.JPanel {

    /**
     * Creates new form listbarang
     */
    public listbarang() {
        initComponents();
        tampil_tabel_barang();
    }
void tampil_tabel_barang (){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("kode barang");
        model.addColumn("nama barang");
                model.addColumn("harga jual");
        model.addColumn("harga beli");
        try{
            String sql="SELECT id_barang, nama_barang, harga_beli, harga_jual FROM barang";
            java.sql.Connection conn=koneksi.ConfigDB();
            java.sql.Statement statement=conn.createStatement();
            java.sql.ResultSet resultSet=statement.executeQuery(sql);
            while(resultSet.next()){
                model.addRow(new Object[]{resultSet.getString("id_barang"),resultSet.getString("nama_barang"),resultSet.getString("harga_beli"),resultSet.getString("harga_jual")});
            }
           ttabelbarang.setModel(model);
        }catch (Exception e){
            e.printStackTrace();
            }
        }
    
void reset(){
        tkodeb.setText("");
    tnamab.setText("");
    
    thargabeli.setText("");
    thargajual.setText("");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tkodeb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tnamab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        thargabeli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        thargajual = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttabelbarang = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(42, 139, 139));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Kode barang");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama barang");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Harga beli");

        thargabeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thargabeliActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Harga jual");

        bsimpan.setBackground(new java.awt.Color(0, 255, 0));
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bubah.setBackground(new java.awt.Color(255, 255, 0));
        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(255, 0, 0));
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        breset.setBackground(new java.awt.Color(0, 0, 255));
        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(thargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnamab, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tkodeb, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(bsimpan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(thargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(breset)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tkodeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tnamab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(thargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(thargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bubah)
                    .addComponent(bsimpan)
                    .addComponent(bhapus)
                    .addComponent(breset))
                .addContainerGap(295, Short.MAX_VALUE))
        );

        ttabelbarang.setBackground(new java.awt.Color(153, 204, 255));
        ttabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttabelbarang.setMaximumSize(new java.awt.Dimension(32767, 32767));
        ttabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttabelbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ttabelbarang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String kode_barang=tkodeb.getText();
        String nama_barang=tnamab.getText();
        
        int harga_jual=Integer.parseInt(thargajual.getText());
        int harga_beli=Integer.parseInt(thargabeli.getText());
        try{
            String sql="INSERT INTO barang(id_barang,nama_barang,harga_beli,harga_jual)values('"+kode_barang+"','"+nama_barang+"','"+harga_beli+"','"+harga_jual+"')";
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di simpan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_barang();
        reset();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
        String kode_barang=tkodeb.getText();
        String nama_barang=tnamab.getText();
        String harga_jual=thargajual.getText();
        String harga_beli=thargabeli.getText();
        try{
            String sql = "UPDATE barang SET nama_barang='" + nama_barang + "', harga_jual='" + harga_jual + "', harga_beli='" + harga_beli + "' WHERE id_barang='" + kode_barang + "'";

            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di ubah");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_barang();
        reset();
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        String kode_barang=tkodeb.getText();

        try{
            String sql="DELETE FROM barang WHERE id_barang='"+kode_barang+"'";
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_barang();
        reset();
    }//GEN-LAST:event_bhapusActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetActionPerformed

    private void thargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thargabeliActionPerformed

    private void ttabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttabelbarangMouseClicked
        // TODO add your handling code here:
        int baris=ttabelbarang.rowAtPoint(evt.getPoint());
        String id_barang=ttabelbarang.getValueAt(baris, 0).toString();
        String nama_barang=ttabelbarang.getValueAt(baris, 1).toString();
        String harga_jual=ttabelbarang.getValueAt(baris, 2).toString();
        String harga_beli=ttabelbarang.getValueAt(baris, 3).toString();
         tkodeb.setText(id_barang);
         tnamab.setText(nama_barang);
          thargabeli.setText(harga_beli);
         thargajual.setText(harga_jual);
         tkodeb.setEditable(false);
    }//GEN-LAST:event_ttabelbarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField thargabeli;
    private javax.swing.JTextField thargajual;
    private javax.swing.JTextField tkodeb;
    private javax.swing.JTextField tnamab;
    private javax.swing.JTable ttabelbarang;
    // End of variables declaration//GEN-END:variables
}
