
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author zainu
 */
public class supplier extends javax.swing.JPanel {

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
            reset();
        tampil_tabel_supplier();
    }
    
    void tampil_tabel_supplier (){
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("kode supplier");
        model.addColumn("nama supplier");
        model.addColumn("telepon");
        model.addColumn("email");
        model.addColumn("alamat");
        try{
            String sql="SELECT * FROM supplier";
            java.sql.Connection conn=koneksi.ConfigDB();
            java.sql.Statement statement=conn.createStatement();
            java.sql.ResultSet resultSet=statement.executeQuery(sql);
            while(resultSet.next()){
                model.addRow(new Object[]{resultSet.getString("kode_supplier"),
                    resultSet.getString("nama_supplier"),resultSet.getString("telepon"),
                    resultSet.getString("email"),resultSet.getString("alamat")});
            }
           ttabelsup.setModel(model);
        }catch (Exception e){
            e.printStackTrace();
            }
        }
    
void reset(){
    tkodes.setText("");
    tnamas.setText("");
    tt.setText("");
    te.setText("");
    ta.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tkodes = new javax.swing.JTextField();
        tnamas = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        te = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttabelsup = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setText("Kode supplier");

        jLabel2.setText("Nama supplier");

        jLabel3.setText("Telepon");

        jLabel4.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        bsimpan.setBackground(new java.awt.Color(0, 255, 0));
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bubah.setBackground(new java.awt.Color(255, 255, 51));
        bubah.setText("Ubah");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(255, 0, 0));
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        breset.setBackground(new java.awt.Color(0, 0, 255));
        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        ttabelsup.setBackground(new java.awt.Color(0, 204, 204));
        ttabelsup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ttabelsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttabelsupMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ttabelsup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(te, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(tt)
                            .addComponent(tnamas)
                            .addComponent(tkodes))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(breset))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tkodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tnamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(te, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bubah)
                    .addComponent(bhapus)
                    .addComponent(breset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
         String kode_supplier=tkodes.getText();
        String nama_supplier=tnamas.getText();
        String telepon=tt.getText();
        String email=te.getText();
        String alamat=ta.getText();
        try{
            String sql="INSERT INTO supplier(kode_supplier,nama_supplier,telepon,email,alamat)"
                    + "values('"+kode_supplier+"','"+nama_supplier+"','"+telepon+"','"+email+"','"+alamat+"')";
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di simpan");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_supplier();
        reset();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void ttabelsupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttabelsupMouseClicked
        // TODO add your handling code here:
        int baris= ttabelsup.rowAtPoint(evt.getPoint());
        String kode_supplier= ttabelsup.getValueAt(baris, 0).toString();
        String nama_supplier= ttabelsup.getValueAt(baris, 1).toString();
        String telepon= ttabelsup.getValueAt(baris, 2).toString();
        String email= ttabelsup.getValueAt(baris, 3).toString();
        String alamat= ttabelsup.getValueAt(baris, 4).toString();
         tkodes.setText(kode_supplier);
         tnamas.setText(nama_supplier);
         tt.setText(telepon);
         te.setText(email);
         ta.setText(alamat);
         tkodes.setEditable(false);
    }//GEN-LAST:event_ttabelsupMouseClicked

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
         String kode_supplier=tkodes.getText();
        
        try{
            String sql="DELETE FROM supplier WHERE kode_supplier='"+kode_supplier+"'";
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_supplier();
        reset();
    }//GEN-LAST:event_bhapusActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
        // TODO add your handling code here:
         String kode_supplier=tkodes.getText();
        String nama_supplier=tnamas.getText();
        String telepon=tt.getText();
        String email=te.getText();
        String alamat=ta.getText();
        try{
             String sql = "UPDATE supplier SET nama_supplier='" + nama_supplier+ "', "
                     + "telepon='" + telepon + "', email='" + email + "',"
                     + " alamat='" + alamat + "' WHERE kode_supplier='" + kode_supplier + "'";
            java.sql.Connection conn =koneksi.ConfigDB();
            java.sql .Statement statement=conn.createStatement();
            statement.execute(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di ubah");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_tabel_supplier();
        reset();
    }//GEN-LAST:event_bubahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhapus;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField te;
    private javax.swing.JTextField tkodes;
    private javax.swing.JTextField tnamas;
    private javax.swing.JTextField tt;
    private javax.swing.JTable ttabelsup;
    // End of variables declaration//GEN-END:variables
}
